# Homework 5
## Kyle Hadley

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
import cvxpy as cp
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

In [2]:
import warnings
warnings.simplefilter('ignore')

## 1. Linear Program Duality

Given the linear program $p^* = \min\limits_x c^Tx$ s.t. $Ax = b, Cx \geq d$.

### (a)

We can write the linear program, $p^*$, in it's game form such that we are minimizing $x$ and maximizing $(v, w)$ of our Lagrangian. Solving for our lagrangian,

$$\mathcal{L}(x, v, w) = f(x) + v^Tg(x) + w^Th(x) = c^Tx + v^T(Ax-b) + w^T(Cx - d)$$
$$\mathcal{L}(x, v, w) = (c^T + v^TA + w^TC)x - v^Tb - w^Td$$

Thus, we find that 
$$p^* = \min\limits_x \max\limits_{v, w} \mathcal{L}(x, v, w)$$
$$\text{s.t. } \mathcal{L}(x, v, w) = (c^T + v^TA + w^TC)x - v^Tb - w^Td$$

### (b)

To find a relationship between $p^*$ and $d^*$, we can start with the relationship of

$$\mathcal{L}(x, v) \;|\; \forall x, \forall v \leq \max_x \mathcal{L}(x, v) \; | \; \forall v$$

If we minimize $v$ on both sides the relationship still holds true that

$$\min_v \mathcal{L}(x, v) \;|\; \forall x \leq \min_v (\max_x \mathcal{L}(x, v))$$

Next, we can see that for any $x$ selected for the left-hand side of our equation, the relationship holds true. Thus we can pick an $x$ that maximizes the left-hand side (i.e. $\max_x$) such that

$$\max_x (\min_v \mathcal{L}(x, v)) \leq \min_v (\max_x \mathcal{L}(x, v))$$

Thus, we can see that from this relationship and our definitions for $p^*$ and $d^*$, $p^* \leq d^*$.

### (c)

Taking the derivative of the Lagrangian, as found in part (a), with respect to $x$ we find and equate the relationship to $0$, as we are minimizing $x$,

$$\frac{\partial \mathcal{L}}{\partial x} = c^T + v^TA + \mu^TC = 0$$

Thus, we find the condition $c^T + v^TA + \mu^TC = 0$.

### (d)

Given our constraint as found in part (c), we can write the appropriate objective function of $v$ and $w$, $\mathcal{l}(v,w)$ as follows,

$$p^* = \max\limits_{v, w} (- v^Tb - \mu^Td)$$

s.t. $g(v, w) = 0$ and $h(v,w) \geq 0$.

### (e)

Given the values for $c^T$, $A$, $b$, $C$, and $d$, we can solve both the primal and dual versions using cvxpy as shown below.

In [19]:
# Establish our values for input parameters
A = np.matrix([[1, 1, 1, 1, 1], [1, 1, -1, 0, 0], [0, 0, 0, 1, -1]])
b = np.matrix([[1], [0], [0]])
c = np.matrix([1, 2, 4, 5, 6])
C_prime = np.matrix([[-1, -1, -1, 0, 0], [0, 0, 0, -1, -1]])
C = np.concatenate((np.identity(5), C_prime), axis=0)
d = np.matrix([[0], [0], [0], [0], [0], [-0.5], [-0.5]])

#print(A, b, c, C, d)

# Define and solve the CVXPY problem.
x = cp.Variable(shape=(5, 1))
prob = cp.Problem(cp.Minimize(c @ x), [A @ x == b, C @ x >= d])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value, '\n', prob.constraints[1].dual_value)


The optimal value is 3.9999999998358136
A solution x is
[[2.50000000e-01]
 [2.41013141e-11]
 [2.50000000e-01]
 [2.50000000e-01]
 [2.50000000e-01]]
A dual solution is
[[-5.80414113]
 [ 1.5       ]
 [ 0.5       ]] 
 [[4.61842945e-10]
 [1.00000000e+00]
 [5.79071862e-10]
 [1.22463856e-10]
 [1.22463889e-10]
 [3.30414113e+00]
 [3.04141131e-01]]


### (f)



## 2. Quadratic Program Duality

Consider the quadratic program $p^* = min_x \frac{1}{2}x^TQx + r^Tx$ s.t. $Ax = b, Cx \geq d$.

## 3. Simplex optimization



### (a)

a - $\begin{bmatrix}1 & 0 & 0 \end{bmatrix}^T$

b - $\begin{bmatrix}0 & 1 & 0 \end{bmatrix}^T$

c - $\begin{bmatrix}0 & 0 & 1 \end{bmatrix}^T$

d - $\begin{bmatrix}\frac{1}{2} & \frac{1}{2} & 0 \end{bmatrix}^T$

e - $\begin{bmatrix}0 & \frac{1}{2} & \frac{1}{2} \end{bmatrix}^T$

f - $\begin{bmatrix}\frac{1}{2} & 0 & \frac{1}{2} \end{bmatrix}^T$

g - $\begin{bmatrix}\frac{1}{3} & \frac{1}{3} & \frac{1}{3} \end{bmatrix}^T$

h - $x_2 = 1 - x_1$

i - $x_3 = 1 - x_2$

j - $x_1 = 1 - x_3$

k - $r^T + \begin{bmatrix}0 & 0 & 1 \end{bmatrix}^T$

l - $r^T + \begin{bmatrix}\frac{1}{3} & \frac{1}{3} & \frac{1}{3} \end{bmatrix}^T$

m - $r^T + \begin{bmatrix}0 & 1 & 0 \end{bmatrix}^T$

n - $\begin{bmatrix}\frac{1}{3} & \frac{1}{3} & 0 \end{bmatrix}^T$

o - $\begin{bmatrix}\frac{1}{3} & \frac{1}{3} & \frac{1}{3} \end{bmatrix}^T$

p - $r^T$

### (b)

a - $r_1$

b - $r_2$

c - $r_3$

d - $\mu_1$

e - $\mu_2$

f - $\mu_3$

g - $\lambda$

h - $\mu_1^*$

i - $\mu_3^*$

j - $\lambda^*$

k - $x_2$

## 4. Dynamic Programming

### (a)

Assuming that in our diagram our states are numbered from top to bottom ($state = \{1, 2, 3\}$) and time is numbered from left to right ($time = \{0, 1, 2, 3, 4\}$ - time $5$ is ignored because their is our final "red" node), the optimal "cost-to-go" for each node to the end is calculated as follows:

---
$time = 4$, $state = 1$ - 2

$time = 4$, $state = 2$ - 2

$time = 4$, $state = 3$ - 1

---

$time = 3$, $state = 1$ - 3

$time = 3$, $state = 2$ - 2

$time = 3$, $state = 3$ - 3

---

$time = 2$, $state = 1$ - 5

$time = 2$, $state = 2$ - 4

$time = 2$, $state = 3$ - 4

---

$time = 1$, $state = 1$ - 5

$time = 1$, $state = 2$ - 6

$time = 1$, $state = 3$ - 6

---

$time = 0$, $state = 2$ - 6

### (b)

The shortest path is start node ("blue" node) $\rightarrow$ time = 1, state 1 $\rightarrow$ time = 2, state = 2 $\rightarrow$ time = 3, state = 2 $\rightarrow$ time = 4, state = 3 $\rightarrow$ end node ("red" node).